### ISSUE TITLE
vue

### ISSUE THREAD

**Issue by Zlmdb** [kakajun/auto-generate-md#1]
只能用于vue工程吗？

**Comment by kakajun** [comment]
暂时只支持了vue哦，你的是react么？



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 30, 2023 16:08 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [kakajun/auto-generate-md] vue (Issue #1)




 
只能用于vue工程吗？
